### PR TITLE
feat: CI/CD workflow for handling PRs

### PR DESCRIPTION
**Pull request by YohannesTz**
### PR Summary

This pull request introduces a new CI/CD workflow named **"Build and Distribute (Staging)"** designed to handle pull requests and branch pushes for the `dev`, `master`, and `main` branches. Here’s a summary of its key features:

1. **Trigger Events**:
   - The workflow is triggered by push events to the `dev`, `master`, and `main` branches.
   - It also triggers when pull requests are opened or reopened on these branches.

2. **Build Process**:
   - **Checkout Code**: The workflow begins by checking out the repository code using `actions/checkout@v2`.
   - **Notify Contributors**: Sends a notification to a specified Telegram chat with details about the build, including commit information, diffs, and pull request details.
   - **Setup JDK and Flutter**: Configures JDK 17 using `actions/setup-java@v1` and sets up Flutter using the version specified in secrets or environment variables, defaulting to `3.4.4` if not provided.
   - **Build**: Executes a custom script (`build-and-filter-errors.sh`) to build the APK, filtering errors and saving logs.

3. **Error Handling**:
   - **Send Error Logs**: If the build fails, sends the error logs to the Telegram chat, regardless of the build outcome.

4. **Generate SHA**:
   - Generates shortened SHA values for the commit and compares them with the base and head commits of the pull request, storing them in environment variables.

5. **Send Build Artifacts**:
   - Sends the built APK file to the Telegram chat, along with detailed build and commit information, providing visibility into the build process and results.

This workflow streamlines the build and distribution process for the staging environment, ensuring that relevant stakeholders are notified of build status and artifacts are made available for review.

### CODE REVIEW

**Comment by AbhiTheModder** [comment]
> 5. **Send Build Artifacts**:
>    
>    * Sends the built APK file to the Telegram chat, along with detailed build and commit information, providing visibility into the build process and results.

Does ScholArxiv have a telegram channel?

**Comment by YohannesTz** [comment]
Hi @AbhiTheModder I don't think it has one. but I guess if @dagmawibabi merges this PR. we would have a group for ScholArxiv which the workflow will send to. so not yet! 😅

**Comment by AbhiTheModder** [comment]
> we would have a group for ScholArxiv which the workflow will send to. so not yet! 😅

Cool, but I think you should rebase your commits they feel like spam tbh

**Comment by dagmawibabi** [comment]
Thank you for making my life easier, this is very good DX 🔥 @YohannesTz

**Pull request merged**
