### PR TITLE
implemented sort function

### LINKED ISSUE #32: [FEATURE]: Sort by date
A simple sort feature where users can sort the search results by published date

### PR DESCRIPTION
**Pull request by EYOB123695**
Added 'Sort by Date' Functionality with Arrow Icon on AppBar (Fixes #32)"

Description:

Implemented a feature to sort papers by date.
Added an arrow icon on the AppBar to toggle between ascending (oldest first) and descending (newest first) sort order.
The arrow icon dynamically changes direction based on the selected sort order.
Solved issue #32.

### CODE REVIEW

**Comment by dagmawibabi** [comment]
@EYOB123695 this's an awesome edition, can you send screenshots/video/gif as well?

**Comment by EYOB123695** [comment]
Here is a video

**Comment by dagmawibabi** [comment]
@EYOB123695 video missing, hmm

**Comment by EYOB123695** [comment]
https://github.com/user-attachments/assets/062fc329-a8a6-4f3a-a967-f04eb1c9092b

**Comment by dagmawibabi** [comment]
@EYOB123695 great job. One issue is that the icon doesn't make any sense try to find a different icon or maybe use a sort icono, and also can u put the icon on the left side of the search icon?

**Comment by EYOB123695** [comment]
https://github.com/user-attachments/assets/0bf6fd81-ef5d-4f3e-b492-8ee3edbc6f45

Updated the icon and moved it to the left of search

**Comment by dagmawibabi** [comment]
Awesome looks really nice! simple and clean! Merged!

**Pull request merged**
