### PR TITLE
Code style refactor

### PR DESCRIPTION
**Pull request by eban12**
Minor code changes based on recommendations from the official Dart style guide. The full guide can be found at https://dart.dev/effective-dart/style

### CODE REVIEW

**Comment by dagmawibabi** [comment]
Okay these changes make my life easier and thank you so much!!

Can you explain all the new changes to the ios and macos files tho? @eban12 
image

**Comment by eban12** [comment]
> Can you explain all the new changes to the ios and macos files tho?
Those were auto generated when running the app on my mac for the first time. The Podfile is required to make the app build for ios and mac. I am not sure why it removed the webview though.

**Comment by dagmawibabi** [comment]
have you tried running it for iOS? or Mac? and did it run? If so can you send screenshots?

**Comment by eban12** [comment]
> have you tried running it for iOS? or Mac? and did it run? If so can you send screenshots? @eban12

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 03 46 51

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 03 54 23

**Comment by dagmawibabi** [comment]
@eban12 does everything work on the IOS version?

**Comment by eban12** [comment]
### As far as I can tell everything works as it used to


Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 19 56

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 19 44

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 19 40

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 19 27

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 19 21

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 18 31

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 03 54 23

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 03 46 51

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 20 26

**Comment by eban12** [comment]
Here is the pdf viewer

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-02 at 04 27 53

**Comment by eban12** [comment]
You can also pull https://github.com/eban12/ScholArxiv.git locally and verify that all is well I guess.

**Comment by dagmawibabi** [comment]
@eban12 I am actually happy to see it run on iOS cause I haven't had the chance to try it so far. I guess I don't have to make a lot of changes when I publish to iOS.

**Comment by eban12** [comment]
hey @dagmawibabi let me know if there is anything missing from this PR :)

**Comment by dagmawibabi** [comment]
@eban12 beautiful and delightful work! Makes readability and maintenance very nice.

**Pull request merged**
